### ISSUE TITLE
YOLOv5 validation fails with PL and DDP

### ISSUE THREAD

**Issue by Anjum48** [airctic/icevision#1048]
## 🐛 Bug
**Describe the bug**
I am trying to run YOLOv5 in PyTorch Lighting using DDP with 2 GPUs. On the validation sanity check I'm seeing this error:

```
  | Name  | Type  | Params
--------------------------------
0 | model | Model | 35.3 M
--------------------------------
35.3 M    Trainable params
0         Non-trainable params
35.3 M    Total params
70.552    Total estimated model params size (MB)
Validation sanity check: 100%|██████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.45s/it]Error executing job with overrides: ['model=yolov5']
Traceback (most recent call last):
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in run_stage
    return self._run_train()
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1306, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1370, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 109, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 122, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 217, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 236, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 444, in validation_step
    return self.model(*args, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 92, in forward
    output = self.module.validation_step(*inputs, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/icevision/models/ultralytics/yolov5/lightning/model_adapter.py", line 54, in validation_step
    loss = self.compute_loss(training_out, yb)[0]
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/yolov5/utils/loss.py", line 120, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/yolov5/utils/loss.py", line 191, in build_targets
    r = t[:, :, 4:6] / anchors[:, None]  # wh ratio
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anjum/kaggle/tensorflow-great-barrier-reef/train_iv.py", line 76, in run_fold
    trainer.fit(model, datamodule=dm)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in fit
    self._call_and_handle_interrupt(
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 695, in _call_and_handle_interrupt
    self.training_type_plugin.reconciliate_processes(traceback.format_exc())
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 533, in reconciliate_processes
    raise DeadlockDetectedException(f"DeadLock detected from rank: {self.global_rank} \n {trace}")
pytorch_lightning.utilities.exceptions.DeadlockDetectedException: DeadLock detected from rank: 1 
 Traceback (most recent call last):
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in run_stage
    return self._run_train()
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1306, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1370, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 109, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 122, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 217, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 236, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 444, in validation_step
    return self.model(*args, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 92, in forward
    output = self.module.validation_step(*inputs, **kwargs)
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/icevision/models/ultralytics/yolov5/lightning/model_adapter.py", line 54, in validation_step
    loss = self.compute_loss(training_out, yb)[0]
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/yolov5/utils/loss.py", line 120, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/home/anjum/anaconda3/envs/kaggle/lib/python3.9/site-packages/yolov5/utils/loss.py", line 191, in build_targets
    r = t[:, :, 4:6] / anchors[:, None]  # wh ratio
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

```

Looking at the code in the Ultralytics repo, I think that `yolov5/utils/loss.py` has had some recent updates that might(?) fix this? This will require an updated version of `yolov5-icevision`

**To Reproduce**
1. Build an IceVision YOLOv5 model with PL adapter
2. Train with ddp

**Expected behavior**
No error should be shown when loss is computed during validation

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - PyTorch: 1.10.1
 - PL: 1.5.3

**Additional context**

**Comment by potipot** [comment]
Hi Anjum, thanks for reporting this. We havent had the chance to run this part of the code on mutliple GPUs so this went unnoticed. Looking at the currently installed `yolov5-icevision` version of 6.0.0 there aren't any explicit calls to operation that move tensors between devices. ( `tensor.to(device=torch.device("cuda"))`, `.cuda()` or similar).

My guessing is that this error comes from one of these, whereas pytorch-lightning advises to refrain from device calls. Could you please confirm that your part of the code adheres to pytorch-lightning distributed training guidelines posted here https://pytorch-lightning.readthedocs.io/en/latest/accelerators/gpu.html#delete-cuda-or-to-calls.

**Comment by Anjum48** [comment]
Hi @potipot, yes my code doesn't have any `.cuda()` or device calls. DDP works fine with mmdet models (tested with YOLOX and RetinaNet), so I think it's specific to YOLOv5

**Comment by FraPochetti** [comment]
This might be hard to solve, if not impossible.
We have always had issues with YOLOv5 device management, due to how the loss is instantiated.
This happens before the model is created and weights are loaded, creating all sorts of problems even when it comes to CPU vs GPU, let alone 2 GPUs :)
I am afraid we can't do anything about this :(
I know it's a solution but try sticking to a single GPU.
