### ISSUE TITLE
Convert model to TorchScript

### ISSUE THREAD

**Issue by turgut090** [airctic/icevision#859]
Hi. I trained the model with [icevision](https://github.com/airctic/icevision/blob/master/notebooks/YOLOv5.ipynb). However, I could not find out a proper way to export the model with export.py to TorchScript model. https://github.com/ultralytics/yolov5/blob/master/models/export.py
Saving the weights of yolo5 throws the following:

```
torch.save(model.state_dict(), "models/yolo.pth")
python export.py --weights ~/Documents/imageai/models/yolo.pt
Namespace(weights='/home/turgut/Documents/imageai/models/yolo.pt', img_size=[640, 640], batch_size=1, device='cpu', include=['torchscript', 'onnx', 'coreml'], half=False, inplace=False, train=False, optimize=False, dynamic=False, simplify=False, opset_version=12)
YOLOv5 🚀 v5.0-180-ge8c5237 torch 1.7.1+cu110 CPU

Traceback (most recent call last):
  File "/home/turgut/Documents/yolov5/models/export.py", line 165, in <module>
    export(**vars(opt))
  File "/home/turgut/Documents/yolov5/models/export.py", line 47, in export
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/turgut/Documents/yolov5/models/experimental.py", line 120, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
KeyError: 'model'

```
If I save the model, then I get:

```
torch.save(model, "model.pth")
Namespace(weights='/home/turgut/Documents/imageai/model.pth', img_size=[640, 640], batch_size=1, device='cpu', include=['torchscript', 'onnx', 'coreml'], half=False, inplace=False, train=False, optimize=False, dynamic=False, simplify=False, opset_version=12)
YOLOv5 🚀 v5.0-180-ge8c5237 torch 1.7.1+cu110 CPU

Traceback (most recent call last):
  File "/home/turgut/Documents/yolov5/models/export.py", line 165, in <module>
    export(**vars(opt))
  File "/home/turgut/Documents/yolov5/models/export.py", line 47, in export
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/turgut/Documents/yolov5/models/experimental.py", line 119, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "/home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Model' object has no attribute 'param_groups_fn'

```

**Comment by turgut090** [comment]
Not sure but is it the correct form?

```
import torch
model.eval()
input_tensor = torch.rand(1,3,320,320).to(torch.device("cuda") )

script_model = torch.jit.trace(model,input_tensor, strict=False)
script_model.save("yolo5.torchscript.pt")
```

**Comment by lgvaz** [comment]
> Not sure but is it the correct form?
Can you check if loading the exported model afterward gives you the correct results?

---
For the script from ultralytics, we probably don't have the exact same format of the model they have. I do believe we can change our code to replicate exactly the same thing though

**Comment by turgut090** [comment]
The prediction returns a tuple. So, the output is the same I believe:

```

import torch


model.eval()
input_tensor = torch.rand(1,3,320,320).to(torch.device("cuda") )

script_model = torch.jit.trace(model,input_tensor, strict=False)
script_model.save("yolo5.torchscript.pt")

original = model(input_tensor)
ported = script_model(input_tensor)

torch.all(torch.eq(original[0],ported[0]))
torch.all(torch.eq(original[1][1],ported[1][1]))
torch.all(torch.eq(original[1][2],ported[1][2]))
```

```
>>> input_tensor = torch.rand(1,3,320,320).to(torch.device("cuda") )
>>> 
>>> script_model = torch.jit.trace(model,input_tensor, strict=False)
/home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/yolov5/models/yolo.py:50: 
TracerWarning:
Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow 
of Python values, so this value will be treated as a constant in the future. This means that the trace might not 
generalize to other inputs!
  if self.grid[i].shape[2:4] != x[i].shape[2:4]:
>>> script_model.save("yolo5.torchscript.pt")
>>> 
>>> original = model(input_tensor)
>>> ported = script_model(input_tensor)
>>> 
>>> torch.all(torch.eq(original[0],ported[0]))
tensor(True, device='cuda:0')
>>> torch.all(torch.eq(original[1][1],ported[1][1]))
tensor(True, device='cuda:0')
>>> torch.all(torch.eq(original[1][2],ported[1][2]))
tensor(True, device='cuda:0')
```

**Comment by turgut090** [comment]
I am working with this example: https://github.com/pytorch/android-demo-app/tree/master/ObjectDetection
The Yolo5s TorchScript model generated from the original repo works fine. However, my model trained with icevision fails.

**Comment by rsomani95** [comment]
@turgut090 can you give us a fully reproducible example? I have had success converting the yolov5 model provided by icevision by copying over bits from the export script from ultralytics.

In your first comment:

```bash
torch.save(model.state_dict(), "models/yolo.pth")
python export.py --weights ~/Documents/imageai/models/yolo.pt
```

You seem to be saving and providing a diff model to the export script. Also, saving the `state_dict` won't work. The export script's `--weights` actually expects a torchscript model that is provided by ultralytics.

To make it work with icevision, you'll have to write the model loading code yourself. The process would roughly look something like:
1. Import model definition
2. Load your custom weights
3. Copy over bits from the export script to run over your model

**Comment by turgut090** [comment]
This is what I was doing: https://colab.research.google.com/drive/1JaF6PJT6wmxJYatGLK-tjvy3Y4jT1UgF?usp=sharing

**Comment by m-ali-awan** [comment]
Hi Turgut, hope you are fine.
Are you able to solve this, as I want to use this model for tracking so I want real time inference. For that I need to convert this to plain pytorch or ONNX.

Thanks for any help.

**Comment by m-ali-awan** [comment]
@turgut090 ,
But I am not able to get that much good results with ultralytics, as with icevision.
