### ISSUE TITLE
mask_rcnn.fastai.learner fails with empty annotations

### ISSUE THREAD

**Issue by jaeeolma** [airctic/icevision#913]
## 🐛 Bug
**Describe the bug**

mask_rcnn.fastai.learner fails when it encounters an image with empty mask annotations. I'm not sure whether this is because of icevision, fastai, albumentations or some other thing.

**To Reproduce**
I've encountered two cases where this bug appears: 

1. Have a dataset where some images have no annotations:

```
for r in train_ds.records:
    if len(r.detection.areas) == 0: 
        print(r)

--------------------------------------------------------------------------

BaseRecord

common: 
	- Record ID: 651
	- Filepath: ../data/hiidenportti/processed/7_Hiidenportti_Chunk5_orto/raster_tiles/R0C1.tif
	- Img: None
	- Image size ImgSize(width=500, height=500)
detection: 
	- Areas: []
	- Class Map: <ClassMap: {'background': 0, 'Standing': 1, 'Fallen': 2}>
	- Labels: []
	- BBoxes: []
	- Is Crowds: []
	- Masks: <EncodedRLEs with 0 objects>
...
```

Then depending on where to force the bug to reappear the error message is either

```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-35-69752bdd55ee> in <module>
----> 1 learn.dls.one_batch()

/opt/conda/lib/python3.8/site-packages/fastai/data/load.py in one_batch(self)
    146     def one_batch(self):
    147         if self.n is not None and len(self)==0: raise ValueError(f'This DataLoader does not contain any batches')
--> 148         with self.fake_l.no_multiproc(): res = first(self)
    149         if hasattr(self, 'it'): delattr(self, 'it')
    150         return res

/opt/conda/lib/python3.8/site-packages/fastcore/basics.py in first(x, f, negate, **kwargs)
    545     x = iter(x)
    546     if f: x = filter_ex(x, f=f, negate=negate, gen=True, **kwargs)
--> 547     return next(x, None)
    548 
    549 # Cell

/opt/conda/lib/python3.8/site-packages/fastai/data/load.py in __iter__(self)
    107         self.before_iter()
    108         self.__idxs=self.get_idxs() # called in context of main process (not workers/subprocesses)
--> 109         for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
    110             if self.device is not None: b = to_device(b, self.device)
    111             yield self.after_batch(b)

/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py in __next__(self)
    515             if self._sampler_iter is None:
    516                 self._reset()
--> 517             data = self._next_data()
    518             self._num_yielded += 1
    519             if self._dataset_kind == _DatasetKind.Iterable and \

/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    555     def _next_data(self):
    556         index = self._next_index()  # may raise StopIteration
--> 557         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    558         if self._pin_memory:
    559             data = _utils.pin_memory.pin_memory(data)

/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     32                 raise StopIteration
     33         else:
---> 34             data = next(self.dataset_iter)
     35         return self.collate_fn(data)
     36 

/opt/conda/lib/python3.8/site-packages/fastai/data/load.py in create_batches(self, samps)
    116         if self.dataset is not None: self.it = iter(self.dataset)
    117         res = filter(lambda o:o is not None, map(self.do_item, samps))
--> 118         yield from map(self.do_batch, self.chunkify(res))
    119 
    120     def new(self, dataset=None, cls=None, **kwargs):

/opt/conda/lib/python3.8/site-packages/fastcore/basics.py in chunked(it, chunk_sz, drop_last, n_chunks)
    214     if not isinstance(it, Iterator): it = iter(it)
    215     while True:
--> 216         res = list(itertools.islice(it, chunk_sz))
    217         if res and (len(res)==chunk_sz or not drop_last): yield res
    218         if len(res)<chunk_sz: return

/opt/conda/lib/python3.8/site-packages/fastai/data/load.py in do_item(self, s)
    131     def prebatched(self): return self.bs is None
    132     def do_item(self, s):
--> 133         try: return self.after_item(self.create_item(s))
    134         except SkipItemException: return None
    135     def chunkify(self, b): return b if self.prebatched else chunked(b, self.bs, self.drop_last)

/opt/conda/lib/python3.8/site-packages/fastai/data/load.py in create_item(self, s)
    138     def retain(self, res, b):  return retain_types(res, b[0] if is_listy(b) else b)
    139     def create_item(self, s):
--> 140         if self.indexed: return self.dataset[s or 0]
    141         elif s is None:  return next(self.it)
    142         else: raise IndexError("Cannot index an iterable dataset numerically - must use `None`.")

/opt/conda/lib/python3.8/site-packages/icevision/data/dataset.py in __getitem__(self, i)
     33 
     34     def __getitem__(self, i):
---> 35         record = self.records[i].load()
     36         if self.tfm is not None:
     37             record = self.tfm(record)

/opt/conda/lib/python3.8/site-packages/icevision/core/record.py in load(self)
     64     def load(self) -> "BaseRecord":
     65         record = deepcopy(self)
---> 66         record.reduce_on_components("_load")
     67         return record
     68 

/opt/conda/lib/python3.8/site-packages/icevision/core/components/composite.py in reduce_on_components(self, fn_name, reduction, **fn_kwargs)
     74         results = {}
     75         for task, composite in self.task_composites.items():
---> 76             result = composite.reduce_on_components(fn_name, reduction, **fn_kwargs)
     77             results[task] = result
     78 

/opt/conda/lib/python3.8/site-packages/icevision/core/components/composite.py in reduce_on_components(self, fn_name, reduction, **fn_kwargs)
    123         results = []
    124         for component in self.components:
--> 125             results.append(getattr(component, fn_name)(**fn_kwargs))
    126 
    127         if reduction is not None and len(results) > 0:

/opt/conda/lib/python3.8/site-packages/icevision/core/record_components.py in _load(self)
    396 
    397     def _load(self):
--> 398         self.masks = MaskArray.from_masks(
    399             self.masks, self.composite.height, self.composite.width
    400         )

/opt/conda/lib/python3.8/site-packages/icevision/core/mask.py in from_masks(cls, masks, h, w)
    108         # HACK: check for backwards compatibility
    109         if isinstance(masks, EncodedRLEs):
--> 110             return masks.to_mask(h, w)
    111         else:
    112             masks_arrays = [o.to_mask(h=h, w=w).data for o in masks]

/opt/conda/lib/python3.8/site-packages/icevision/core/mask.py in to_mask(self, h, w)
     50 
     51     def to_mask(self, h, w) -> "MaskArray":
---> 52         mask = mask_utils.decode(self.erles)
     53         mask = mask.transpose(2, 0, 1)  # channels first
     54         return MaskArray(mask)

/opt/conda/lib/python3.8/site-packages/pycocotools/mask.py in decode(rleObjs)
     87 def decode(rleObjs):
     88     if type(rleObjs) == list:
---> 89         return _mask.decode(rleObjs)
     90     else:
     91         return _mask.decode([rleObjs])[:,:,0]

pycocotools/_mask.pyx in pycocotools._mask.decode()

MemoryError: Unable to allocate 0 bytes for an array with shape (93840161203584, 0, 0) and data type uint8
```

Or 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-37-d81c6bd29d71> in <module>
----> 1 learn.lr_find()

/opt/conda/lib/python3.8/site-packages/fastai/callback/schedule.py in lr_find(self, start_lr, end_lr, num_it, stop_div, show_plot, suggestions)
    220     n_epoch = num_it//len(self.dls.train) + 1
    221     cb=LRFinder(start_lr=start_lr, end_lr=end_lr, num_it=num_it, stop_div=stop_div)
--> 222     with self.no_logging(): self.fit(n_epoch, cbs=cb)
    223     if show_plot: self.recorder.plot_lr_find()
    224     if suggestions:

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    216             self.opt.set_hypers(lr=self.lr if lr is None else lr)
    217             self.n_epoch = n_epoch
--> 218             self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
    219 
    220     def _end_cleanup(self): self.dl,self.xb,self.yb,self.pred,self.loss = None,(None,),(None,),None,None

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    158 
    159     def _with_events(self, f, event_type, ex, final=noop):
--> 160         try: self(f'before_{event_type}');  f()
    161         except ex: self(f'after_cancel_{event_type}')
    162         self(f'after_{event_type}');  final()

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in _do_fit(self)
    207         for epoch in range(self.n_epoch):
    208             self.epoch=epoch
--> 209             self._with_events(self._do_epoch, 'epoch', CancelEpochException)
    210 
    211     def fit(self, n_epoch, lr=None, wd=None, cbs=None, reset_opt=False):

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    158 
    159     def _with_events(self, f, event_type, ex, final=noop):
--> 160         try: self(f'before_{event_type}');  f()
    161         except ex: self(f'after_cancel_{event_type}')
    162         self(f'after_{event_type}');  final()

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in _do_epoch(self)
    201 
    202     def _do_epoch(self):
--> 203         self._do_epoch_train()
    204         self._do_epoch_validate()
    205 

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in _do_epoch_train(self)
    193     def _do_epoch_train(self):
    194         self.dl = self.dls.train
--> 195         self._with_events(self.all_batches, 'train', CancelTrainException)
    196 
    197     def _do_epoch_validate(self, ds_idx=1, dl=None):

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    158 
    159     def _with_events(self, f, event_type, ex, final=noop):
--> 160         try: self(f'before_{event_type}');  f()
    161         except ex: self(f'after_cancel_{event_type}')
    162         self(f'after_{event_type}');  final()

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in all_batches(self)
    164     def all_batches(self):
    165         self.n_iter = len(self.dl)
--> 166         for o in enumerate(self.dl): self.one_batch(*o)
    167 
    168     def _do_one_batch(self):

/opt/conda/lib/python3.8/site-packages/fastai/data/load.py in __iter__(self)
    107         self.before_iter()
    108         self.__idxs=self.get_idxs() # called in context of main process (not workers/subprocesses)
--> 109         for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
    110             if self.device is not None: b = to_device(b, self.device)
    111             yield self.after_batch(b)

/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py in __next__(self)
    515             if self._sampler_iter is None:
    516                 self._reset()
--> 517             data = self._next_data()
    518             self._num_yielded += 1
    519             if self._dataset_kind == _DatasetKind.Iterable and \

/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1177             if len(self._task_info[self._rcvd_idx]) == 2:
   1178                 data = self._task_info.pop(self._rcvd_idx)[1]
-> 1179                 return self._process_data(data)
   1180 
   1181             assert not self._shutdown and self._tasks_outstanding > 0

/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1223         self._try_put_index()
   1224         if isinstance(data, ExceptionWrapper):
-> 1225             data.reraise()
   1226         return data
   1227 

/opt/conda/lib/python3.8/site-packages/torch/_utils.py in reraise(self)
    427             # have message field
    428             raise self.exc_type(message=msg)
--> 429         raise self.exc_type(msg)
    430 
    431 

TypeError: __init__() missing 1 required positional argument: 'dtype'
```

2. Remove empty annotations, but don't specify `shift_scale_rotate=None` for `tfms.A.aug_tfms`

Remove them for instance like this:

```
faulty_ixs = []

for i, r in enumerate(train_ds.records):
    if len(r.detection.areas) == 0:
        faulty_ixs.append(i)
for i, f in enumerate(faulty_ixs):
    train_ds.records.pop(f-i)
    
faulty_ixs = []

for i, r in enumerate(valid_ds.records):
    if len(r.detection.areas) == 0:
        faulty_ixs.append(i)
for i, f in enumerate(faulty_ixs):
    valid_ds.records.pop(f-i)
```

Now with learner the error is 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-47-d81c6bd29d71> in <module>
----> 1 learn.lr_find()

/opt/conda/lib/python3.8/site-packages/fastai/callback/schedule.py in lr_find(self, start_lr, end_lr, num_it, stop_div, show_plot, suggestions)
    220     n_epoch = num_it//len(self.dls.train) + 1
    221     cb=LRFinder(start_lr=start_lr, end_lr=end_lr, num_it=num_it, stop_div=stop_div)
--> 222     with self.no_logging(): self.fit(n_epoch, cbs=cb)
    223     if show_plot: self.recorder.plot_lr_find()
    224     if suggestions:

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    216             self.opt.set_hypers(lr=self.lr if lr is None else lr)
    217             self.n_epoch = n_epoch
--> 218             self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
    219 
    220     def _end_cleanup(self): self.dl,self.xb,self.yb,self.pred,self.loss = None,(None,),(None,),None,None

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    158 
    159     def _with_events(self, f, event_type, ex, final=noop):
--> 160         try: self(f'before_{event_type}');  f()
    161         except ex: self(f'after_cancel_{event_type}')
    162         self(f'after_{event_type}');  final()

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in _do_fit(self)
    207         for epoch in range(self.n_epoch):
    208             self.epoch=epoch
--> 209             self._with_events(self._do_epoch, 'epoch', CancelEpochException)
    210 
    211     def fit(self, n_epoch, lr=None, wd=None, cbs=None, reset_opt=False):

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    158 
    159     def _with_events(self, f, event_type, ex, final=noop):
--> 160         try: self(f'before_{event_type}');  f()
    161         except ex: self(f'after_cancel_{event_type}')
    162         self(f'after_{event_type}');  final()

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in _do_epoch(self)
    201 
    202     def _do_epoch(self):
--> 203         self._do_epoch_train()
    204         self._do_epoch_validate()
    205 

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in _do_epoch_train(self)
    193     def _do_epoch_train(self):
    194         self.dl = self.dls.train
--> 195         self._with_events(self.all_batches, 'train', CancelTrainException)
    196 
    197     def _do_epoch_validate(self, ds_idx=1, dl=None):

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    158 
    159     def _with_events(self, f, event_type, ex, final=noop):
--> 160         try: self(f'before_{event_type}');  f()
    161         except ex: self(f'after_cancel_{event_type}')
    162         self(f'after_{event_type}');  final()

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in all_batches(self)
    164     def all_batches(self):
    165         self.n_iter = len(self.dl)
--> 166         for o in enumerate(self.dl): self.one_batch(*o)
    167 
    168     def _do_one_batch(self):

/opt/conda/lib/python3.8/site-packages/fastai/data/load.py in __iter__(self)
    107         self.before_iter()
    108         self.__idxs=self.get_idxs() # called in context of main process (not workers/subprocesses)
--> 109         for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
    110             if self.device is not None: b = to_device(b, self.device)
    111             yield self.after_batch(b)

/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py in __next__(self)
    515             if self._sampler_iter is None:
    516                 self._reset()
--> 517             data = self._next_data()
    518             self._num_yielded += 1
    519             if self._dataset_kind == _DatasetKind.Iterable and \

/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1197             else:
   1198                 del self._task_info[idx]
-> 1199                 return self._process_data(data)
   1200 
   1201     def _try_put_index(self):

/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1223         self._try_put_index()
   1224         if isinstance(data, ExceptionWrapper):
-> 1225             data.reraise()
   1226         return data
   1227 

/opt/conda/lib/python3.8/site-packages/torch/_utils.py in reraise(self)
    427             # have message field
    428             raise self.exc_type(message=msg)
--> 429         raise self.exc_type(msg)
    430 
    431 

ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data = next(self.dataset_iter)
  File "/opt/conda/lib/python3.8/site-packages/fastai/data/load.py", line 118, in create_batches
    yield from map(self.do_batch, self.chunkify(res))
  File "/opt/conda/lib/python3.8/site-packages/fastai/data/load.py", line 144, in do_batch
    def do_batch(self, b): return self.retain(self.create_batch(self.before_batch(b)), b)
  File "/opt/conda/lib/python3.8/site-packages/icevision/engines/fastai/adapters/convert_dataloader_to_fastai.py", line 14, in create_batch
    return (dataloader.collate_fn, raise_error_convert)[self.prebatched](b)
  File "/opt/conda/lib/python3.8/site-packages/icevision/models/utils.py", line 87, in inner
    record.unload()
  File "/opt/conda/lib/python3.8/site-packages/icevision/core/record.py", line 70, in unload
    self.reduce_on_components("_unload")
  File "/opt/conda/lib/python3.8/site-packages/icevision/core/components/composite.py", line 76, in reduce_on_components
    result = composite.reduce_on_components(fn_name, reduction, **fn_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/icevision/core/components/composite.py", line 125, in reduce_on_components
    results.append(getattr(component, fn_name)(**fn_kwargs))
  File "/opt/conda/lib/python3.8/site-packages/icevision/core/record_components.py", line 404, in _unload
    self.masks = self.masks.to_erles(self.composite.height, self.composite.width)
  File "/opt/conda/lib/python3.8/site-packages/icevision/core/mask.py", line 85, in to_erles
    mask_utils.encode(np.asfortranarray(self.data.transpose(1, 2, 0)))
ValueError: axes don't match array
```

**Expected behavior**

If I recall correctly icevision should support empty annotations right? 

For now, I can work with this by removing data with no annotations and specifying `shift_scale_rotate=None` to `aug_tfms`.

**Desktop:**

- OS: Ubuntu 20.04
- python==3.8.10
- fastai==2.3.1
- fastcore==1.3.26
- icevision==0.8.1
- albumentations==0.5.2
- torch==1.8.1
- torchvision==0.9.1
- pillow==0.8.2
- pycocotools==2.0.
- cv2==4.5.3

**Comment by lgvaz** [comment]
Hmm.. I think the incoming branch `unet3` might fix this issue.

@jaeeolma can you checkout that branch and check if the problem still persists?

**Comment by jaeeolma** [comment]
Problem with `shift_scale_rotate` is solved by branch `unet3`. I ran `learn.dls.one_batch()` 1000 times without error. 

However, in the case of empty annotations the following happens, no matter whether `shift_scale_rotate` is `None` or not:

```
train_tfms = tfms.A.Adapter([*tfms.A.aug_tfms(size=400), 
                             tfms.A.Normalize()])
valid_tfms = tfms.A.Adapter([tfms.A.Normalize()])
train_ds = Dataset(train, train_tfms)
valid_ds = Dataset(valid, valid_tfms)

mask_rcnn = models.torchvision.mask_rcnn

train_dl = mask_rcnn.train_dl(train_ds, batch_size=16, shuffle=True, num_workers=4)
valid_dl = mask_rcnn.valid_dl(valid_ds, batch_size=16, shuffle=False, num_workers=4)

# Use AP[.50:.05:.95] as metric to monitor
metrics = [COCOMetric(metric_type=COCOMetricType.mask)]

model = mask_rcnn.model(num_classes=len(class_map))
learn = mask_rcnn.fastai.learner(dls=[train_dl, valid_dl], model=model, metrics=metrics)

# Force the bug to reappear
for _ in range(100):
    b = learn.dls.one_batch()
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-24-406c7f0383e7> in <module>
      1 for _ in range(100):
----> 2     b = learn.dls.one_batch()

~/miniconda3/envs/ice/lib/python3.9/site-packages/fastai/data/load.py in one_batch(self)
    146     def one_batch(self):
    147         if self.n is not None and len(self)==0: raise ValueError(f'This DataLoader does not contain any batches')
--> 148         with self.fake_l.no_multiproc(): res = first(self)
    149         if hasattr(self, 'it'): delattr(self, 'it')
    150         return res

~/miniconda3/envs/ice/lib/python3.9/site-packages/fastcore/basics.py in first(x, f, negate, **kwargs)
    545     x = iter(x)
    546     if f: x = filter_ex(x, f=f, negate=negate, gen=True, **kwargs)
--> 547     return next(x, None)
    548 
    549 # Cell

~/miniconda3/envs/ice/lib/python3.9/site-packages/fastai/data/load.py in __iter__(self)
    107         self.before_iter()
    108         self.__idxs=self.get_idxs() # called in context of main process (not workers/subprocesses)
--> 109         for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
    110             if self.device is not None: b = to_device(b, self.device)
    111             yield self.after_batch(b)

~/miniconda3/envs/ice/lib/python3.9/site-packages/torch/utils/data/dataloader.py in __next__(self)
    515             if self._sampler_iter is None:
    516                 self._reset()
--> 517             data = self._next_data()
    518             self._num_yielded += 1
    519             if self._dataset_kind == _DatasetKind.Iterable and \

~/miniconda3/envs/ice/lib/python3.9/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    555     def _next_data(self):
    556         index = self._next_index()  # may raise StopIteration
--> 557         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    558         if self._pin_memory:
    559             data = _utils.pin_memory.pin_memory(data)

~/miniconda3/envs/ice/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     32                 raise StopIteration
     33         else:
---> 34             data = next(self.dataset_iter)
     35         return self.collate_fn(data)
     36 

~/miniconda3/envs/ice/lib/python3.9/site-packages/fastai/data/load.py in create_batches(self, samps)
    116         if self.dataset is not None: self.it = iter(self.dataset)
    117         res = filter(lambda o:o is not None, map(self.do_item, samps))
--> 118         yield from map(self.do_batch, self.chunkify(res))
    119 
    120     def new(self, dataset=None, cls=None, **kwargs):

~/miniconda3/envs/ice/lib/python3.9/site-packages/fastcore/basics.py in chunked(it, chunk_sz, drop_last, n_chunks)
    214     if not isinstance(it, Iterator): it = iter(it)
    215     while True:
--> 216         res = list(itertools.islice(it, chunk_sz))
    217         if res and (len(res)==chunk_sz or not drop_last): yield res
    218         if len(res)<chunk_sz: return

~/miniconda3/envs/ice/lib/python3.9/site-packages/fastai/data/load.py in do_item(self, s)
    131     def prebatched(self): return self.bs is None
    132     def do_item(self, s):
--> 133         try: return self.after_item(self.create_item(s))
    134         except SkipItemException: return None
    135     def chunkify(self, b): return b if self.prebatched else chunked(b, self.bs, self.drop_last)

~/miniconda3/envs/ice/lib/python3.9/site-packages/fastai/data/load.py in create_item(self, s)
    138     def retain(self, res, b):  return retain_types(res, b[0] if is_listy(b) else b)
    139     def create_item(self, s):
--> 140         if self.indexed: return self.dataset[s or 0]
    141         elif s is None:  return next(self.it)
    142         else: raise IndexError("Cannot index an iterable dataset numerically - must use `None`.")

/mnt/d/Users/E1005164/icevision/icevision/data/dataset.py in __getitem__(self, i)
     35         record = self.records[i].load()
     36         if self.tfm is not None:
---> 37             record = self.tfm(record)
     38         else:
     39             # HACK FIXME

/mnt/d/Users/E1005164/icevision/icevision/tfms/transform.py in __call__(self, record)
      9         # TODO: this assumes record is already loaded and copied
     10         # which is generally true
---> 11         return self.apply(record)
     12 
     13     @abstractmethod

/mnt/d/Users/E1005164/icevision/icevision/tfms/albumentations/albumentations_adapter.py in apply(self, record)
    285         # collect results
    286         for collect_op in sorted(self._collect_ops, key=lambda x: x.order):
--> 287             collect_op.fn(record)
    288 
    289         return record

/mnt/d/Users/E1005164/icevision/icevision/tfms/albumentations/albumentations_adapter.py in collect(self, record)
    134 
    135     def collect(self, record):
--> 136         masks = self.adapter._filter_attribute(self.adapter._albu_out["masks"])
    137         masks = MaskArray(np.array(masks))
    138         self._record_component.set_mask_array(masks)

/mnt/d/Users/E1005164/icevision/icevision/tfms/albumentations/albumentations_adapter.py in _filter_attribute(self, v)
    304         if self._keep_mask is None:
    305             return v
--> 306         assert len(v) == len(self._keep_mask)
    307         return [o for o, keep in zip(v, self._keep_mask) if keep]
    308 

AssertionError: 
```

Granted, there is a chance that my annotations are a lot wonkier than I'd like to admit (I'm converting shapefiles to coco-format) and that might cause some issues.

**Comment by jaeeolma** [comment]
Seems that this can be resolved by modifying `icevision/tfms/albumentations/albumentations_adapter.py` to read

```
def _filter_attribute(self, v: list):
    if self._keep_mask is None or len(self._keep_mask) == 0: # check whether self._keep_mask is an empty list
        return v
    assert len(v) == len(self._keep_mask)
    return [o for o, keep in zip(v, self._keep_mask) if keep] 
```

Because it's fairly common that `len(v) == 1` as `v` is a mask full of zeroes, but `len(self._keep_mask) == 0` as `self._keep_mask` is an empty list. Someone more familiar with icevision could tell if this will break something else.

**Comment by lgvaz** [comment]
Hmm.. Interesting, I *think* this should not break anything

Can you open a PR for it?

**Comment by rbavery** [comment]
@jaeeolma Thanks for opening this issue and PR, I'm keen to see this merged! I'm training the fastai learner for a torchvision maskrcnn model and I'm getting COCOMetrics all equal to -1 https://github.com/SkyTruth/ceruleanserver/blob/d99074f360966c0a2c231ec4c36b808ea5614793/ml/notebooks/icevision_demo.ipynb

**Comment by FraPochetti** [comment]
This should be solved.
